version: '3.8'
services:
  router:
    build:
      context: .
      dockerfile: dockerfiles/main.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "5000:5000"
    volumes:
      - ./main:/app/main
      - ./utils:/app/utils
      - ./models:/app/models
    entrypoint: ["uvicorn", "main.fragment_hub:app", "--host", "0.0.0.0", "--port", "5000"]

  neucon:
    build:
      context: .
      dockerfile: dockerfiles/neucon.Dockerfile
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - SERVER_URL=ws://router:5000/ws/model
      - MODEL_NAME=neucon
    volumes:
      - ./models:/app/models
      - ./utils:/app/utils
      - ./scripts:/app/scripts
      - ./configs:/app/configs
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

    entrypoint: ["/app/docker_entrypoint.sh"]

  slam3r:
    build:
      context: .
      dockerfile: dockerfiles/slam3r.Dockerfile
    environment:
      - SERVER_URL=ws://router:5000/ws/model
      - MODEL_NAME=slam3r
    volumes:
      - ./models:/app/models
      - ./utils:/app/utils
      - ./scripts:/app/scripts
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

    entrypoint: ["/app/docker_entrypoint.sh"]
