version: '3.8'
services:
  router:
    build:
      context: .
      dockerfile: dockerfiles/main.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "5000:5000"
    volumes:
      - ./main:/app/main
      - ./common_utils:/app/common_utils
      - ./models:/app/models
      - ./db:/app/db
    entrypoint: ["uvicorn", "main.fragment_hub:app", "--host", "0.0.0.0", "--port", "5000"]

  neucon:
    build:
      context: .
      dockerfile: dockerfiles/neucon.Dockerfile
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - SERVER_URL=ws://router:5000/ws/model
      - MODEL_NAME=neucon
    volumes:
      - ./models:/app/models
      - ./common_utils:/app/common_utils
      - ./scripts:/app/scripts
      - ./configs:/app/configs
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

    entrypoint: ["/app/docker_entrypoint.sh"]

  visfusion:
    build:
      context: .
      dockerfile: dockerfiles/visfusion.Dockerfile
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - SERVER_URL=ws://router:5000/ws/model
      - MODEL_NAME=visfusion
    volumes:
      - ./models:/app/recon_models
      - ./common_utils:/app/common_utils
      - ./scripts:/app/scripts
      - ./configs:/app/configs
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

    entrypoint: ["/app/recon_models/VisFusion/docker_entrypoint.sh"]

  slam3r:
    build:
      context: .
      dockerfile: dockerfiles/slam3r.Dockerfile
    environment:
      - SERVER_URL=ws://router:5000/ws/model
      - MODEL_NAME=slam3r
    volumes:
      - ./models:/app/models
      - ./common_utils:/app/common_utils
      - ./scripts:/app/scripts
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

    entrypoint: ["/app/docker_entrypoint.sh"]

  mast3r:
    build:
      context: .
      dockerfile: dockerfiles/mast3r.Dockerfile
    environment:
      - SERVER_URL=ws://router:5000/ws/model
      - MODEL_NAME=mast3r
    volumes:
      - ./common_utils:/app/common_utils
      - ./scripts:/app/scripts
      - ./configs:/app/configs
      - mast3r-envs:/opt/conda/envs
    shm_size: "8gb"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    entrypoint: ["/app/models/MASt3R/docker_entrypoint.sh"]

volumes:
  mast3r-envs: