version: '3.8'
services:
  router:
    build:
      context: .
      dockerfile: docker/main.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "5000:5000"
    volumes:
      - ./main:/app/main
      - ./models:/app/models
    entrypoint: ["uvicorn", "main.fragment_hub:app", "--host", "0.0.0.0", "--port", "5000"]

  neucon:
    build:
      context: .
      dockerfile: docker/neucon.Dockerfile
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - SERVER_URL=ws://router:5000/ws/model
      - MODEL_NAME=neucon
    volumes:
      - ./models:/app/models
      - ./scripts:/app/scripts
      - ./configs:/app/configs
    runtime: nvidia
    entrypoint: ["conda", "run", "--no-capture-output", "-n", "neucon", "env", "PYTHONUNBUFFERED=1", "python", "/app/scripts/neucon_main.py", "--cfg", "/app/configs/neucon.yaml"]


  # modelB:
    # Another container for a different model